title: You have arrived!
author: kaycog
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Kaycog's github-pages-with-jekyll 
  
Theme: minima


# social links
# twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  kaycog # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
