title: You have arrived 
author: GitHub User Kaycog
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description of my site. 
Theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  kaycog # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
